# import pr-timeline-item.gql

query morePrTimelineItems($owner: String!, $repoName: String!, $itemNumber: Int!, $cursor: String) {
  repository(owner: $owner, name: $repoName) {
    pullRequest(number: $itemNumber) {
      timelineItems(first: 100, after: $cursor) {
        pageInfo {
          hasNextPage
          endCursor
        }
        edges {
          node {
            ...prTimelineItem
          }
        }
      }
    }
  }
}
