const categories = {
    tooNegative: [] as string[],
    meToo: [] as string[],
    lickCookie: [] as string[],
    impatient: [] as string[],
    anyUpdates: [] as string[]
};

categories.tooNegative.push("Why isn't this implemented yet? Too bad the devs don't care about this project");
categories.tooNegative.push("Unfortunately this issue is totally neglected, for no reason");
categories.tooNegative.push("TypeScript is totally unusable without this feature, disaster of a language really");
categories.tooNegative.push("In before the mods just lock this and walk away. Ignoring all of us");
categories.tooNegative.push("Someone should just fork this project and get some maintainers who give a crap. Clearly the ones here don't.");

categories.meToo.push("Need this for my project");
categories.meToo.push("Same here");
categories.meToo.push("Yes please");
categories.meToo.push("Absolute must-have feature in my opinion");
categories.meToo.push("Plus one.");

categories.lickCookie.push("Hey there! Mind if I take a crack at this bug?");
categories.lickCookie.push("Can I help with this bug?");
categories.lickCookie.push("Is it alright if I work on this bug?");
categories.lickCookie.push("May I work on this bug, please?");
categories.lickCookie.push("Hi! I'm interested in tackling this bug. Is that okay?");
categories.lickCookie.push("Would it be alright if I took a shot at this bug?");
categories.lickCookie.push("Hey, can I contribute to fixing this bug?");
categories.lickCookie.push("Is it fine if I jump in and work on this bug?");
categories.lickCookie.push("Mind if I give this bug a shot?");
categories.lickCookie.push("Could I potentially work on this bug, if that's alright?");
categories.lickCookie.push("Can I have a go at fixing this bug?");
categories.lickCookie.push("Is it okay if I work on this bug? I'd be happy to help.");
categories.lickCookie.push("Would it be acceptable if I took up this bug?");
categories.lickCookie.push("Hi! I'd like to offer my assistance with this bug. May I?");
categories.lickCookie.push("Hey, I'm interested in fixing this bug. Can I proceed?");
categories.lickCookie.push("Can I take ownership of this bug and work on it?");
categories.lickCookie.push("Hey! Mind if I lend a hand in resolving this bug?");
categories.lickCookie.push("May I have permission to work on this bug, please?");
categories.lickCookie.push("Can I join the efforts in fixing this bug?");
categories.lickCookie.push("Is it okay for me to tackle this bug? I have some ideas.");
categories.lickCookie.push("I'd like to help with this bug. Is that alright with you?");
categories.lickCookie.push("Can I contribute my skills to this bug?");
categories.lickCookie.push("Would it be okay if I take on this bug and try to fix it?");
categories.lickCookie.push("Is it alright if I work on this bug? I think I can help.");
categories.lickCookie.push("Hey, I'd love to help squash this bug. Can I get involved?");
categories.lickCookie.push("Can I take a shot at fixing this bug, if that's okay?");
categories.lickCookie.push("Mind if I lend my expertise to this bug?");
categories.lickCookie.push("Is it acceptable if I work on this bug? I'm confident I can help.");
categories.lickCookie.push("Can I have permission to contribute to fixing this bug?");
categories.lickCookie.push("Hey there! Can I give this bug a try?");
categories.lickCookie.push("May I offer my assistance in resolving this bug?");
categories.lickCookie.push("Would it be alright if I took up the challenge of fixing this bug?");
categories.lickCookie.push("Hi! I'd like to work on this bug, if that's alright with you.");
categories.lickCookie.push("Can I be assigned to this bug so I can start working on it?");
categories.lickCookie.push("Is it okay if I contribute to fixing this bug? I have some ideas.");
categories.lickCookie.push("Hey, I'm eager to help with this bug. May I proceed?");
categories.lickCookie.push("Can I have a go at tackling this bug? I think I can help.");
categories.lickCookie.push("Mind if I take ownership of this bug and work on it?");
categories.lickCookie.push("Is it alright if I lend a hand in resolving this bug?");
categories.lickCookie.push("May I work on this bug? I'd be happy to assist in its resolution.");
categories.lickCookie.push("Can I work on this?");
categories.lickCookie.push("I'd like to try fixing the issue if that's okay");
categories.lickCookie.push("Can I send a pull request to fix this?");
categories.lickCookie.push("Is anyone else investigating already?");

categories.anyUpdates.push("Any news on this issue?");
categories.anyUpdates.push("Can you provide an update?");
categories.anyUpdates.push("Is there any progress?");
categories.anyUpdates.push("Can you tell me where we stand?");
categories.anyUpdates.push("Is this still being worked on?");
categories.anyUpdates.push("When can we expect an update?");
categories.anyUpdates.push("Is there a timeline for resolution?");
categories.anyUpdates.push("Have you made any progress?");
categories.anyUpdates.push("Is there anything new to report?");
categories.anyUpdates.push("What's the latest on this?");
categories.anyUpdates.push("Any updates coming soon?");
categories.anyUpdates.push("Are there any developments?");
categories.anyUpdates.push("Is anyone looking into this?");
categories.anyUpdates.push("Do you have any updates for us?");
categories.anyUpdates.push("Any movement on this issue?");
categories.anyUpdates.push("Any news on when this will be fixed?");
categories.anyUpdates.push("Can we get an update, please?");
categories.anyUpdates.push("Is there a status update?");
categories.anyUpdates.push("Any updates on the horizon?");
categories.anyUpdates.push("Do we have any updates on this bug?");
categories.anyUpdates.push("Is there any activity on this issue?");
categories.anyUpdates.push("Can we get a progress report?");
categories.anyUpdates.push("Any updates since the last time?");
categories.anyUpdates.push("Is anyone actively working on this?");
categories.anyUpdates.push("Can we expect a fix anytime soon?");
categories.anyUpdates.push("Is there a resolution in sight?");
categories.anyUpdates.push("Are there any updates we should know about?");
categories.anyUpdates.push("Any updates on the GitHub issue?");
categories.anyUpdates.push("Is there anything new to report on this matter?");
categories.anyUpdates.push("Can you provide an update on the status?");
categories.anyUpdates.push("Do we have any updates on the fix?");
categories.anyUpdates.push("Has there been any progress made on this?");
categories.anyUpdates.push("Can we get an ETA on the resolution?");
categories.anyUpdates.push("Any news on when this will be addressed?");
categories.anyUpdates.push("Is there any information on the progress?");
categories.anyUpdates.push("Are there any updates on the GitHub issue?");
categories.anyUpdates.push("Any updates since the last status report?");
categories.anyUpdates.push("Is there a chance we can get an update soon?");
categories.anyUpdates.push("Can we get any updates on this issue, please?");
categories.anyUpdates.push("Has there been any movement on this matter?");

categories.impatient.push("Suggested 2 years ago, any plans to implement this feature?");
categories.impatient.push("It's been 3 years since this feature was suggested, any updates on its progress?");
categories.impatient.push("This feature request is now 4 years old, is it still being considered?");
categories.impatient.push("It's been quite a while since this feature was suggested, any recent developments?");
categories.impatient.push("Has there been any progress on this feature request? It was suggested 6 months ago.");
categories.impatient.push("This feature was suggested 1 year ago, any chance of seeing it in the near future?");
categories.impatient.push("Two years have passed since this feature was suggested, any updates on its status?");
categories.impatient.push("It's been a significant amount of time since this feature was suggested, any reasons for the delay?");
categories.impatient.push("This feature request is now 3 years old, is there any timeline for its implementation?");
categories.impatient.push("Any plans to work on this feature? It has been 2 years since it was suggested.");
categories.impatient.push("It's been 4 years since this feature was suggested, any roadmap for its implementation?");
categories.impatient.push("Has there been any progress on this feature request? It has been 6 months without updates.");
categories.impatient.push("This feature was suggested 1 year ago, any insights on its current status?");
categories.impatient.push("Two years have passed since this feature was suggested, is there any hope for its implementation?");
categories.impatient.push("It's been quite some time since this feature was suggested, any chance of getting an update?");
categories.impatient.push("This feature request is now 3 years old, any plans to prioritize it?");
categories.impatient.push("Any news on this feature request? It has been 2 years since it was suggested.");
categories.impatient.push("It's been 4 years since this feature was suggested, any ETA on its implementation?");
categories.impatient.push("Has there been any progress on this feature request? It has been 6 months of silence.");
categories.impatient.push("This feature was suggested 1 year ago, any information on when it might be worked on?");
categories.impatient.push("Two years have passed since this feature was suggested, any feedback on its feasibility?");
categories.impatient.push("It's been a considerable amount of time since this feature was suggested, any updates to share?");
categories.impatient.push("This feature request is now 3 years old, any blockers preventing its implementation?");
categories.impatient.push("Any plans to address this feature request? It has been 2 years since it was suggested.");
categories.impatient.push("It's been 4 years since this feature was suggested, any insights into its priority?");
categories.impatient.push("Has there been any progress on this feature request? It has been 6 months without any activity.");
categories.impatient.push("This feature was suggested 1 year ago, any chance of seeing it in the upcoming releases?");
categories.impatient.push("Two years have passed since this feature was suggested, any thoughts on its potential impact?");
categories.impatient.push("It's been quite some time since this feature was suggested, any plans to revisit it?");
categories.impatient.push("This feature request is now 3 years old, any indications of when it might be implemented?");
categories.impatient.push("Any updates on this feature request? It has been 2 years since it was suggested.");
categories.impatient.push("It's been 4 years since this feature was suggested, any progress made towards its implementation?");
categories.impatient.push("Has there been any recent activity on this feature request? It has been 6 months since the last update.");
categories.impatient.push("This feature was suggested 1 year ago, any reasons for the delay in its implementation?");
categories.impatient.push("Two years have passed since this feature was suggested, any plans to pick it up?");
categories.impatient.push("It's been a considerable amount of time since this feature was suggested, any chance of it being added?");
